import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

test('Administration, catalogue, images privées et persistance', async () => {
  const directory = mkdtempSync(join(tmpdir(), 'santeproche-test-'));
  process.env.DATA_DIR = directory;
  process.env.SEED_DEMO = 'false';
  process.env.NODE_ENV = 'test';
  process.env.LOCAL_POSTGRES = 'false';
  if (process.env.TEST_DATABASE_URL) {
    const databaseName = new URL(process.env.TEST_DATABASE_URL).pathname;
    assert.match(databaseName, /^\/santeproche_test_[a-z0-9_]+$/);
    process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  } else delete process.env.DATABASE_URL;
  delete process.env.OPENAI_API_KEY;
  const { server, db } = await import('./index.js');
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  let cookie = '';
  const api = (path, method = 'GET', data, session = true, headers = {}) => fetch(base + '/api' + path, { method, headers: { ...(session && cookie ? { Cookie: cookie } : {}), ...(data ? { 'Content-Type': 'application/json' } : {}), ...headers }, ...(data ? { body: JSON.stringify(data) } : {}) });
  try {
    assert.equal((await api('/admin/pharmacies')).status, 401);
    assert.equal((await api('/admin/profile')).status, 401);
    assert.deepEqual(await (await api('/auth/status')).json(), { setupRequired: true, authenticated: false });
    assert.equal((await api('/auth/setup', 'POST', { email: 'admin@example.test', password: 'test-password-2026' }, false, { Origin: 'https://external.test' })).status, 403);
    const setup = await api('/auth/setup', 'POST', { email: 'admin@example.test', password: 'test-password-2026' });
    assert.equal(setup.status, 201);
    cookie = setup.headers.get('set-cookie').split(';')[0];
    assert.match(setup.headers.get('set-cookie'), /HttpOnly; SameSite=Strict/);
    assert.notEqual((await db.prepare('SELECT hash FROM admins').get()).hash, 'test-password-2026');
    assert.equal((await api('/auth/setup', 'POST', {})).status, 409);
    const pharmacy = await (await api('/admin/pharmacies', 'POST', { nom: 'Pharmacie de test', telephone: '+235 60000000', adresse: 'Adresse A', ville: 'Ville A' })).json();
    assert.ok(pharmacy.id);
    const medicine = await (await api('/admin/medicaments', 'POST', { designation: 'Produit de test', pharmacie_id: pharmacy.id, prix_public: 2500, quantite: 5, currency: 'XAF' })).json();
    assert.ok(medicine.id);
    assert.equal((await api('/admin/medicaments', 'POST', { ...medicine, prix_public: -1 })).status, 400);
    await api('/admin/pharmacies/' + pharmacy.id, 'PUT', { ...pharmacy, telephone: '+235 61111111', adresse: 'Adresse modifiée' });
    const offer = (await (await api('/medicaments?search=produit')).json()).data[0];
    assert.equal(offer.telephone, '+235 61111111');
    assert.equal(offer.adresse, 'Adresse modifiée');
    assert.equal(offer.currency, 'XAF');
    assert.equal(offer.distance, null);
    assert.equal(offer.statusText, 'Horaires non renseignés');
    assert.deepEqual(await (await api('/assistant/status')).json(), { configured: false });
    const assistant = await (await api('/assistant/search', 'POST', { message: 'Je cherche Produit de test', lat: 0, lng: 0 })).json();
    assert.equal(assistant.mode, 'classic');
    assert.equal(assistant.results.length, 1);
    assert.equal(assistant.results[0].telephone, '+235 61111111');
    assert.equal((await api('/assistant/search', 'POST', { message: 'test', lat: 91, lng: 0 })).status, 400);
    assert.equal((await api('/assistant/search', 'POST', { image: { data: 'test' } })).status, 503);
    assert.equal((await api('/admin/pharmacies/' + pharmacy.id, 'DELETE')).status, 409);
    const clinic = await (await api('/admin/cliniques', 'POST', { nom: 'Clinique de test', ville: 'Ville B', telephone: '+235 62222222' })).json();
    assert.ok(clinic.id);
    assert.equal((await (await api('/etablissements/' + clinic.slug)).json()).telephone, '+235 62222222');
    assert.equal((await api('/admin/cliniques/' + clinic.id, 'PUT', { ...clinic, latitude: 91, longitude: 0 })).status, 400);
    await api('/admin/medicaments/' + medicine.id, 'PUT', { ...medicine, quantite: 0 });
    assert.equal((await (await api('/medicaments')).json()).total, 0);
    await api('/admin/medicaments/' + medicine.id, 'PUT', medicine);
    const image = { data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXZkAAAAASUVORK5CYII=' };
    assert.equal((await api('/admin/upload', 'POST', { data: Buffer.from('<svg/>').toString('base64') })).status, 400);
    const uploaded = await (await api('/admin/upload', 'POST', image)).json();
    assert.equal((await fetch(base + uploaded.url)).headers.get('content-type'), 'image/png');
    assert.equal((await api('/contact', 'POST', { nom: 'Test', email: 'patient@example.test', sujet: 'Test', message: 'Message de test' })).status, 201);
    const prescription = await (await api('/prescriptions', 'POST', { telephone: '+23560000000', accept_contact: true, image })).json();
    assert.ok(prescription.id);
    const imagePath = `/admin/prescriptions/${prescription.id}/image`;
    assert.equal((await api(imagePath, 'GET', undefined, false)).status, 401);
    assert.equal((await api(imagePath)).status, 200);
    assert.equal((await (await api('/admin/requests')).json()).length, 2);
    assert.equal((await (await api('/stats')).json()).pharmacies, 1);
    const secondDB = db.kind === 'sqlite' ? new DatabaseSync(join(directory, 'santeproche.sqlite')) : null;
    const persisted = secondDB ? secondDB.prepare('SELECT data FROM records WHERE kind=? AND id=?').get('pharmacies', pharmacy.id) : await db.prepare('SELECT data FROM records WHERE kind=? AND id=?').get('pharmacies', pharmacy.id);
    assert.equal(JSON.parse(persisted.data).telephone, '+235 61111111');
    secondDB?.close();
    assert.equal((await api('/admin/medicaments/' + medicine.id, 'DELETE')).status, 200);
    assert.equal((await api('/admin/pharmacies/' + pharmacy.id, 'DELETE')).status, 200);
    assert.equal((await api('/auth/logout', 'POST', {})).status, 200);
    assert.equal((await api('/admin/requests')).status, 401);
    assert.equal((await api('/auth/login', 'POST', { email: 'admin@example.test', password: 'wrong' })).status, 401);
    const login = await api('/auth/login', 'POST', { email: 'admin@example.test', password: 'test-password-2026' });
    assert.equal(login.status, 200);
    cookie = login.headers.get('set-cookie').split(';')[0];
    const profile = await (await api('/admin/profile')).json();
    assert.deepEqual(Object.keys(profile).sort(), ['email', 'image', 'nom', 'telephone']);
    assert.equal(profile.nom, '');
    assert.equal((await api('/admin/profile', 'PUT', { ...profile, email: 'new@example.test', current_password: 'wrong' })).status, 400);
    assert.equal((await (await api('/admin/profile')).json()).email, 'admin@example.test');
    assert.equal((await api('/admin/profile', 'PUT', { ...profile, email: 'ADMIN@EXAMPLE.TEST' })).status, 200);
    assert.equal((await (await api('/admin/profile')).json()).email, 'admin@example.test');
    const changed = await api('/admin/profile', 'PUT', { ...profile, nom: 'Administrateur test', telephone: '+235 63333333', image: uploaded.url, email: 'new@example.test', current_password: 'test-password-2026' });
    assert.equal(changed.status, 200);
    assert.equal((await changed.json()).nom, 'Administrateur test');
    assert.equal((await api('/admin/profile/password', 'PUT', { current_password: 'wrong', new_password: 'new-password-test-2026', confirm_password: 'new-password-test-2026' })).status, 400);
    assert.equal((await api('/admin/profile/password', 'PUT', { current_password: 'test-password-2026', new_password: 'short', confirm_password: 'short' })).status, 400);
    assert.equal((await api('/admin/profile/password', 'PUT', { current_password: 'test-password-2026', new_password: 'new-password-test-2026', confirm_password: 'different-password' })).status, 400);
    const oldCookie = cookie;
    const password = await api('/admin/profile/password', 'PUT', { current_password: 'test-password-2026', new_password: 'new-password-test-2026', confirm_password: 'new-password-test-2026' });
    assert.equal(password.status, 200);
    cookie = password.headers.get('set-cookie').split(';')[0];
    assert.notEqual(cookie, oldCookie);
    assert.equal((await api('/admin/profile', 'GET', undefined, true, { Cookie: oldCookie })).status, 401);
    assert.equal((await api('/admin/profile')).status, 200);
    assert.equal((await api('/auth/login', 'POST', { email: 'new@example.test', password: 'test-password-2026' })).status, 401);
    assert.equal((await api('/auth/login', 'POST', { email: 'new@example.test', password: 'new-password-test-2026' })).status, 200);
  } finally {
    await new Promise(resolve => server.close(resolve));
    await db.close();
    rmSync(directory, { recursive: true, force: true });
  }
});
