import { useEffect, useState } from 'react';
import { request, write } from '../data/api.js';
export default function AdminLocations({onBusyChange}) {
  const [rows,setRows]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const reload=()=>request('/admin/locations').then(setRows);
  useEffect(()=>{let active=true;request('/admin/locations').then(data=>{if(active)setRows(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  async function run(action){setBusy(true);onBusyChange?.(true);setError('');setMessage('');try{await action();await reload();}catch(e){setError(e.message);}finally{setBusy(false);onBusyChange?.(false);}}
  async function add(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));await run(async()=>{await write('/admin/locations',data);form.reset();setMessage('Lieu ajouté aux listes des formulaires.');});}
  return <section><h2>Pays, villes et quartiers</h2><p>Ajoutez les lieux proposés à l’inscription. Un quartier peut rester vide pour ajouter simplement une ville. Les informations déjà enregistrées dans les fiches sont conservées.</p>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}<form className="admin-panel" onSubmit={add}><fieldset disabled={busy}><div className="admin-fields">{[['pays','Pays',true],['ville','Ville',true],['quartier','Quartier',false]].map(([name,label,required])=><label className="admin-field" key={name}>{label}<input name={name} maxLength={120} required={required}/></label>)}</div><button className="admin-primary">Ajouter un lieu</button></fieldset></form><div className="admin-requests">{rows.map(row=><article className="admin-panel" key={row.id}><strong>{[row.pays,row.ville,row.quartier].filter(Boolean).join(' · ')}</strong><button type="button" disabled={busy} className="admin-delete" onClick={()=>{if(window.confirm('Retirer ce choix de la liste ? Les fiches existantes seront conservées.'))run(()=>request(`/admin/locations/${row.id}`,{method:'DELETE'}));}}>Retirer</button></article>)}</div></section>;
}
