import { useEffect, useState } from 'react';
import { request, write, assetUrl } from '../data/api.js';
const STATUS={pending:'En attente',approved:'Approuvée',rejected:'À compléter',suspended:'Suspendue'};
export default function AdminPartners({ onBusyChange }) {
  const [items,setItems]=useState([]),[filter,setFilter]=useState('pending'),[reasons,setReasons]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;request('/admin/partners').then(data=>{if(active)setItems(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  async function review(item,action){setBusy(true);onBusyChange?.(true);setError('');setMessage('');try{await write(`/admin/partners/${item.id}/review`,{action,reason:reasons[item.id]||''},'PUT');setItems(await request('/admin/partners'));setMessage(action==='approve'?'Pharmacie approuvée et visible sur le site.':action==='reject'?'Demande renvoyée à la pharmacie avec votre motif.':'Compte suspendu : sa fiche et ses médicaments sont masqués.');}catch(e){setError(e.message);}finally{setBusy(false);onBusyChange?.(false);}}
  return <section className="admin-requests"><h2>Inscriptions des pharmacies</h2><p>Vérifiez le dossier et le justificatif avant de publier une pharmacie. Aucune notification par email n’est envoyée automatiquement.</p><nav className="admin-tabs" aria-label="Statut des inscriptions">{Object.entries({all:'Toutes',...STATUS}).map(([key,label])=><button key={key} aria-pressed={filter===key} disabled={busy} onClick={()=>setFilter(key)}>{label} ({items.filter(item=>key==='all'||item.status===key).length})</button>)}</nav>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}{loading?<p>Chargement des inscriptions…</p>:<>{!items.some(item=>filter==='all'||item.status===filter)&&<p>Aucune inscription dans cette catégorie.</p>}{items.filter(item=>filter==='all'||item.status===filter).map(item=><article className="admin-panel" key={item.id}><h2>{item.profile.nom} · {STATUS[item.status]}</h2><p>Responsable : {item.responsable} · {item.email}</p><p>{[item.profile.adresse,item.profile.ville,item.profile.pays].join(' · ')}</p><p>Téléphone : {item.profile.telephone}</p><p>Reçue le {new Date(item.created).toLocaleString('fr-FR')}</p>{item.profile.description&&<p>{item.profile.description}</p>}{item.profile.image&&<img src={assetUrl(item.profile.image)} alt={`Photo de ${item.profile.nom}`} style={{maxWidth:200,maxHeight:130,objectFit:'contain'}}/>}<p><a href={assetUrl(`/api/admin/partners/${item.id}/document`)} target="_blank" rel="noreferrer">Consulter le justificatif privé</a></p><details><summary>Horaires et position transmis</summary><p>GPS : {item.profile.latitude??'Non renseignée'}, {item.profile.longitude??'Non renseignée'}</p><p>De garde : {item.profile.garde?'Oui':'Non'}</p>{['lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche'].map(day=><p key={day}>{day} : {item.profile[`${day}_ouvert`]==null?'Non renseigné':item.profile[`${day}_ouvert`]?`${item.profile[`${day}_heure_ouverture`]} – ${item.profile[`${day}_heure_fermeture`]}`:'Fermé'}</p>)}</details>{item.reason&&<p>Dernier motif : {item.reason}</p>}{item.status!=='rejected'&&<><label className="admin-field">Motif / message à la pharmacie<textarea aria-label={`Motif pour ${item.profile.nom}`} value={reasons[item.id]||''} maxLength={2000} disabled={busy} onChange={e=>setReasons({...reasons,[item.id]:e.target.value})}/></label><div className="admin-form-actions">{['pending','suspended'].includes(item.status)&&<button className="admin-primary" disabled={busy} onClick={()=>review(item,'approve')}>{item.status==='suspended'?'Réactiver':'Approuver'}</button>}{item.status==='pending'&&<button disabled={busy} onClick={()=>review(item,'reject')}>Demander des corrections</button>}{item.status==='approved'&&<button className="admin-delete" disabled={busy} onClick={()=>review(item,'suspend')}>Suspendre le compte</button>}</div></>}</article>)}</>}</section>;
}
