import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { request, write, fileData, assetUrl } from '../data/api.js';
import { PharmacyFields } from '../components/PharmacyForm.jsx';
import './Partner.css';
import PasswordField from '../components/PasswordField.jsx';

const LABELS={pending:'En attente de validation',approved:'Pharmacie approuvée',rejected:'Informations complémentaires requises',suspended:'Compte suspendu'};
const EMPTY={nom:'',telephone:'',adresse:'',ville:'',quartier:'',pays:'',description:'',email:'',latitude:'',longitude:'',garde:false};
const MEDICINE={designation:'',forme:'',prix_public:'',currency:'',quantite:'',image:''};
async function imageData(file, required=false) {
  if(!file){if(required)throw new Error('Ajoutez un justificatif de votre pharmacie.');return null;}
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>4*1024*1024)throw new Error('Les images doivent être au format JPG, PNG ou WEBP, avec une taille de 4 Mo maximum.');
  return fileData(file);
}
export default function Partner() {
  const registering=useLocation().pathname==='/inscription-pharmacie';
  const [account,setAccount]=useState(undefined),[profile,setProfile]=useState(EMPTY),[photo,setPhoto]=useState(null),[document,setDocument]=useState(null);
  const [medicines,setMedicines]=useState([]),[medicine,setMedicine]=useState(MEDICINE),[productPhoto,setProductPhoto]=useState(null);
  const [tab,setTab]=useState('profile'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const demo=import.meta.env.VITE_GITHUB_PAGES==='true';
  useEffect(()=>{if(demo)return;let active=true;request('/partner/status').then(data=>{if(active){setAccount(data);if(data)setProfile(data.profile);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[demo]);
  useEffect(()=>{if(account?.status!=='approved')return;let active=true;Promise.all([request('/partner/profile'),request('/partner/medicaments')]).then(([p,m])=>{if(active){setProfile(p);setMedicines(m);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[account?.status]);
  const perform=async action=>{setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}};
  async function authenticate(event){event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));await perform(async()=>{
    const data=registering?await write('/partner/register',{...fields,profile,accept_review:fields.accept_review==='on',photo:await imageData(photo),document:await imageData(document,true)}):await write('/partner/login',fields);
    setAccount(data);setProfile(data.profile);setPhoto(null);setDocument(null);setMessage(registering?'Votre demande a été envoyée à l’administration.':'Connexion réussie.');
  });}
  async function saveProfile(event){event.preventDefault();await perform(async()=>{
    if(account.status==='approved'){
      const image=await imageData(photo);const updated={...profile};if(image)updated.image=(await write('/partner/upload',image)).url;
      setProfile(await write('/partner/profile',updated,'PUT'));setPhoto(null);setMessage('Votre fiche est enregistrée et mise à jour sur le site.');
    }else{
      const data=await write('/partner/application',{profile,photo:await imageData(photo),document:await imageData(document)},'PUT');setAccount(data);setProfile(data.profile);setPhoto(null);setDocument(null);setMessage('Votre dossier a été renvoyé pour validation.');
    }
  });}
  async function saveMedicine(event){event.preventDefault();await perform(async()=>{const data={...medicine};const image=await imageData(productPhoto);if(image)data.image=(await write('/partner/upload',image)).url;
    await write(`/partner/medicaments${medicine.id?`/${medicine.id}`:''}`,data,medicine.id?'PUT':'POST');setMedicines(await request('/partner/medicaments'));setMedicine(MEDICINE);setProductPhoto(null);setMessage('Médicament enregistré. Un stock nul le retire des résultats publics.');
  });}
  async function refresh(){await perform(async()=>{const data=await request('/partner/status');setAccount(data);if(data)setProfile(data.profile);});}
  return <main className="partner-page container"><div className="partner-heading"><div><span>Espace professionnel</span><h1>{account?'Mon espace pharmacie':registering?'Inscrire ma pharmacie':'Connexion pharmacie'}</h1><p>{account?'Suivez votre demande et gérez votre établissement.':'Votre fiche sera publiée après vérification par l’administration.'}</p></div>{account&&<button disabled={busy} onClick={()=>perform(async()=>{await write('/partner/logout',{});setAccount(null);setProfile(EMPTY);setMedicines([]);setMedicine(MEDICINE);setPhoto(null);setDocument(null);setProductPhoto(null);setTab('profile');})}>Se déconnecter</button>}</div>
    {demo?<section className="partner-panel"><h2>Inscription disponible avec le backend</h2><p>Cette version GitHub est une démonstration. Les inscriptions réelles seront accessibles lorsque le backend sera hébergé.</p><Link to="/devenir-partenaire-pharmacie">Découvrir l’espace pharmacie</Link></section>:<>
      {error&&<p className="partner-error" role="alert">{error}</p>}{message&&<p className="partner-success" role="status">{message}</p>}
      {account===undefined?<p>Connexion au serveur…</p>:!account?<form className="partner-panel" onSubmit={authenticate}><fieldset disabled={busy}><h2>{registering?'1. Votre compte':'Vos identifiants'}</h2><div className="partner-fields">{registering&&<label>Nom du responsable<input name="responsable" required maxLength={200}/></label>}<label>Email de connexion<input type="email" name="email" required maxLength={200} autoComplete="username"/></label><PasswordField label="Mot de passe" name="password" required minLength={registering?12:undefined} maxLength={256} autoComplete={registering?'new-password':'current-password'}/>{registering&&<PasswordField label="Confirmer le mot de passe" name="confirm_password" required minLength={12} maxLength={256} autoComplete="new-password"/>}</div>
        {registering&&<><p>Choisissez un mot de passe de 12 caractères minimum.</p><h2>2. Votre pharmacie</h2><PharmacyFields value={profile} onChange={setProfile} onPhoto={setPhoto} disabled={busy}/><h2>3. Vérification</h2><label>Justificatif d’autorisation ou document professionnel (photo · 4 Mo maximum)<input aria-label="Justificatif de la pharmacie" type="file" accept="image/jpeg,image/png,image/webp" required onChange={e=>setDocument(e.target.files[0]||null)}/></label><p>Ce justificatif est privé. Seuls votre compte et l’administration peuvent le consulter.</p><label className="partner-check"><input type="checkbox" name="accept_review" required/>J’autorise l’administration à examiner mon dossier et je confirme l’exactitude des informations.</label></>}
        <button className="partner-primary" type="submit">{busy?'Envoi…':registering?'Envoyer ma demande':'Se connecter'}</button></fieldset><p>{registering?<Link to="/espace-pharmacie">Déjà inscrit ? Se connecter</Link>:<Link to="/inscription-pharmacie">Inscrire ma pharmacie</Link>}</p></form>:<>
        <section className={`partner-status partner-status--${account.status}`}><div><strong>{LABELS[account.status]}</strong>{account.reason&&<p>Message de l’administration : {account.reason}</p>}<p>{account.status==='pending'?'Votre fiche n’est pas encore publique. L’administration examine votre dossier.':account.status==='approved'?'Vous pouvez gérer votre profil, vos horaires et vos médicaments.':account.status==='suspended'?'Votre fiche et ses médicaments sont masqués. Contactez l’administration pour réactiver votre compte.':'Corrigez votre dossier ci-dessous puis renvoyez-le pour validation.'}</p></div><button disabled={busy} onClick={refresh}>Actualiser le statut</button></section>
        {account.status==='approved'&&<nav className="partner-tabs" aria-label="Gestion de ma pharmacie"><button aria-pressed={tab==='profile'} disabled={busy} onClick={()=>setTab('profile')}>Mon profil et horaires</button><button aria-pressed={tab==='medicines'} disabled={busy} onClick={()=>setTab('medicines')}>Mes médicaments ({medicines.length})</button><Link to={`/pharmacies/${profile.slug}`}>Voir ma fiche publique</Link></nav>}
        {tab==='medicines'&&account.status==='approved'?<div className="partner-dashboard"><section className="partner-panel"><h2>Mes médicaments</h2><button disabled={busy} onClick={()=>{setMedicine(MEDICINE);setProductPhoto(null);}}>Ajouter un médicament</button>{!medicines.length&&<p>Aucun médicament enregistré.</p>}{medicines.map(item=><article className="partner-medicine" key={item.id}><strong>{item.designation}</strong><p>{item.quantite} disponible(s) · {item.prix_public} {item.currency}</p><button disabled={busy} onClick={()=>{setMedicine(item);setProductPhoto(null);}}>Modifier {item.designation}</button><button disabled={busy} onClick={()=>{if(window.confirm('Supprimer ce médicament de votre pharmacie ?'))perform(async()=>{await request(`/partner/medicaments/${item.id}`,{method:'DELETE'});setMedicines(await request('/partner/medicaments'));if(medicine.id===item.id)setMedicine(MEDICINE);});}}>Supprimer</button></article>)}</section><form className="partner-panel" onSubmit={saveMedicine}><h2>{medicine.id?'Modifier le médicament':'Nouveau médicament'}</h2><fieldset disabled={busy}><div className="partner-fields">{[['designation','Nom du médicament','text',true],['forme','Présentation / dosage','text',false],['prix_public','Prix','number',true],['currency','Devise (ex. XAF)','text',true],['quantite','Quantité disponible','number',true]].map(([key,label,type,required])=><label key={key}>{label}<input type={type} required={required} value={medicine[key]??''} min={type==='number'?0:undefined} step={key==='prix_public'?'0.01':key==='quantite'?'1':undefined} maxLength={key==='currency'?3:200} onChange={e=>setMedicine({...medicine,[key]:e.target.value})}/></label>)}<label className="partner-wide">Image du produit<input aria-label="Image du médicament" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setProductPhoto(e.target.files[0]||null)}/>{medicine.image&&<img className="partner-preview" src={assetUrl(medicine.image)} alt="Image actuelle du médicament"/>}</label></div><button className="partner-primary">Enregistrer le médicament</button></fieldset></form></div>:<form className="partner-panel" onSubmit={saveProfile}><h2>{account.status==='approved'?'Mon profil de pharmacie':'Mon dossier d’inscription'}</h2><PharmacyFields value={profile} onChange={setProfile} onPhoto={setPhoto} disabled={busy||account.status==='suspended'}/>{account.status!=='approved'&&<><a href={assetUrl('/api/partner/document')} target="_blank" rel="noreferrer">Consulter mon justificatif privé</a>{account.status!=='suspended'&&<label>Remplacer le justificatif (optionnel)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setDocument(e.target.files[0]||null)} disabled={busy}/></label>}</>}{account.status!=='suspended'&&<button className="partner-primary" disabled={busy}>{busy?'Enregistrement…':account.status==='approved'?'Enregistrer mon profil':'Renvoyer mon dossier pour validation'}</button>}</form>}
      </>}
    </>}
  </main>;
}
